### ISSUE TITLE
Space leak in hashRounds

### ISSUE THREAD

**Issue by rycee** [PeterScott/pwstore#2]
I played around with high strength values and noticed that the program seems to use a lot of memory.  Created a small test program simply containing

``` haskell
 B.putStrLn =<< makePassword (B.pack "hello") 18
```

Compiling with ghc 6.12.1 and `-O1` and running with `+RTS -hT -K50M` gave the following memory profile:
![Lots of memory](http://i.imgur.com/mqIbh.png)

Tracked it down to the `hashRounds` function.  Switching to explicit recursion (and a bang pattern) as per

``` haskell
hashRounds (!bs) 0 = bs
hashRounds bs rounds = hashRounds (H.hash bs) (rounds - 1)
```

gives this, more pleasant, memory profile:
![Not lots of memory](http://i.imgur.com/H5272.png)

I haven't tested this with the purehaskell branch so I cannot say if it suffers from the same problem.

**Comment by PeterScott** [comment]
Thanks! I've added your patch and pushed version 2.2 to Hackage. I'll have to look at the purehaskell branch later.
