### ISSUE TITLE
Timing attack in verifyPassword

### ISSUE THREAD

**Issue by oakwhiz** [PeterScott/pwstore#9]
I noticed that verifyPassword and verifyPasswordWith both use == to compare the hash of the user's input with the stored hash. This seems to me like a timing attack, since == does not compare in constant time, and the differences in time could potentially be measured. Even though PBKDF2 is being used and such an attack seems unlikely to me, I recommend switching to a constant-time comparison function such as the one shown here: http://www.levigross.com/2014/02/07/constant-time-comparison-functions-in-python-haskell-clojure-java-etc/

https://github.com/PeterScott/pwstore/blob/master/pwstore-fast/Crypto/PasswordStore.hs#L325

https://github.com/PeterScott/pwstore/blob/master/pwstore-purehaskell/Crypto/PasswordStore.hs#L199

**Comment by oakwhiz** [comment]
I tried making some edits but I can't run the tests for some reason.

https://github.com/oakwhiz/pwstore/compare/PeterScott:e4ff3ccddf236fe85548447dbaa5b0b62f31e545...954abf11bd46ec568ab3a74d06b9c1f7af023a5b

```
$ runhaskell Tests.hs

Crypto\PasswordStore.hs:417:0:
     error: missing binary operator before token "("

Crypto\PasswordStore.hs:426:0:
     error: missing binary operator before token "("
phase `C pre-processor' failed (exitcode = 1)
```

**Comment by PeterScott** [comment]
Sorry about the delay; my github notification settings got messed up, and so I missed this pull request. Merged.
